### ISSUE TITLE
conda environment

### ISSUE THREAD

**Issue by foury27** [reyuwei/NIMBLE_model#1]
Hi, I am not able to reproduce your environment to correctly run the demo code. Could you please provide your conda/python package versions as well as cudatookit and cudnn version? Thank you.

**Comment by reyuwei** [comment]
[env.txt](https://github.com/reyuwei/NIMBLE_model/files/9466436/env.txt)

Hi! I attached a package list of my environment, but it contains a lot of redundant packages. Maybe just search for the ones that you think may be different. My gpu driver version is 512.15, cuda is 11.6, cudnn 8.0. 

I think as long as you have pytorch and pytorch3d working, you should be able to run the code.
