### ISSUE TITLE
why hand scale in render.blend is set to 0.006?

### ISSUE THREAD

**Issue by delaprada** [reyuwei/NIMBLE_model#14]
Hi! Thank you for providing such a good work. I try to use NIMBLE to generate some synthetic data. I found that the scale setting in blender is set to 0.006273. I wonder why set the scale to 0.006273?

<img width="954" alt="image" src="https://github.com/reyuwei/NIMBLE_model/assets/40078051/ab422c0f-336d-4f57-a5b9-1fb456fca666">

I know that NIMBLE data is in millimeter unit while MANO data is in meter unit. I should scale by 0.001 to get data in MANO scale. 
This scale of 0.006273 is a bit confusing for me.

If I generate NIMBLE mesh obj and rendered images with scale of 0.006273, I guess the unit would be a problem for model training if I want to evalute the model on other datasets?

Thank you!

**Comment by reyuwei** [comment]
Hi, I can't remember why it is set to 0.006 (probably just a random number to make the hand look the right size). 
But the unit for NIMBLE is indeed in millimeters. You should probably change to 0.001 to match MANO scale if you plan to render images for network training.

**Comment by delaprada** [comment]
> Hi, I can't remember why it is set to 0.006 (probably just a random number to make the hand look the right size). But the unit for NIMBLE is indeed in millimeters. You should probably change to 0.001 to match MANO scale if you plan to render images for network training.

Thank you for your help!
