### ISSUE TITLE
License terms

### ISSUE THREAD

**Issue by mihaibujanca** [reyuwei/NIMBLE_model#16]
Thanks for your work! Could you please consider including a license for the repository?

By default (https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository) no license means "the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work"

Thanks!

**Comment by reyuwei** [comment]
Thanks for the suggestion! I have included an MIT license in the repo.

**Comment by mihaibujanca** [comment]
Great, thank you!
