### ISSUE TITLE
Left hand support?

### ISSUE THREAD

**Issue by fh1999** [reyuwei/NIMBLE_model#2]
How can I get a left hand Nimble model？

**Comment by fh1999** [comment]
@reyuwei

**Comment by reyuwei** [comment]
We only train NIMBLE on right hand side data, so we do not provide a left hand model. You can try to create a left hand result by mirroring the output meshes manually with the following code. 
```
vertices.y *= -1.
all_faces = torch.index_select(all_faces.squeeze(), 1, torch.LongTensor([0,2,1]))
```
