### ISSUE TITLE
How to generate a dataset using this model？

### ISSUE THREAD

**Issue by Greyman-Seu** [reyuwei/NIMBLE_model#4]
This is very wonderful work.
NIMBLE model provides diffuse,spec ,mesh,etc.
But pytorch3d only needs vert, face, texture map to build mesh.
How to use this model to generate synthetic picture.Can you give some examples？

**Comment by reyuwei** [comment]
Hi! I use blender to render synthetic images shown in the paper. I have uploaded the project file with shading and background in google drive link. Please follow thefollowing steps in the readme file for rendering. Thanks!

Render in assets/render.blend
Scale down the meshes and manually assign texture images.
Select non-color for color space of normal and specular textures.

**Comment by gs-ren** [comment]
> 

Thank you for the method.  How can I get the correct m v p matrix while  use Blender to create a synthetic picture? I found that the 2D label value（from .xyz files） cannot be calculated correctly in the synthetic picture. Can you share your method please? @reyuwei

**Comment by reyuwei** [comment]
You can export both intrinsic and extrinsic camera matrix from Blender, then project 3D joints to image. 
I have attached an old script for exporting camera parameters from Blender for reference. Not sure if it works with the latest Blender version. 

[export_camera_from_blender.py](https://github.com/reyuwei/NIMBLE_model/files/10970810/export_camera_from_blender.txt)

**Comment by reyuwei** [comment]
> > 
> 
> Thank you for the method. How can I get the correct m v p matrix while use Blender to create a synthetic picture? I found that the 2D label value（from .xyz files） cannot be calculated correctly in the synthetic picture. Can you share your method please? @reyuwei

You can export both intrinsic and extrinsic camera matrix from Blender, then project 3D joints to image. 
I have attached an old script for exporting camera parameters from Blender for reference. Not sure if it works with the latest Blender version. 

[export_camera_from_blender.py](https://github.com/reyuwei/NIMBLE_model/files/10970810/export_camera_from_blender.txt)
