### ISSUE TITLE
How to adjust NIMBLE's MANO output to real world size

### ISSUE THREAD

**Issue by vra** [reyuwei/NIMBLE_model#5]
Hi @reyuwei ,
Thanks for sharing NIMBLE model to community!

when running `demo.py`, I got `rand_0_manov.xyz` and successfully shown it in visualization. However, I noticed that the scale of vertices in this file is quite large. the mean value of vertices position in my case is `[16.59393144 -61.90396254 -26.14423879]`, even scale by 0.01 (in case the unit is centimeter), the size of hand is not match with  real world hand size. 

Could you give any advice on how to scale the MANO output to real world scale? Thanks in advance!

**Comment by reyuwei** [comment]
Hi! The original MRI data and our NIMBLE model are both in millimeter unit. So you probably want to scale by 0.001 to get MANO scale (in meter unit).

**Comment by vra** [comment]
Hi @reyuwei , Thanks for your reply, which solved my problem 👍
