### ISSUE TITLE
convert to MANO

### ISSUE THREAD

**Issue by gs-ren** [reyuwei/NIMBLE_model#8]
Hi, I want  use NIMBLE model to ctreate some  synthetic  data  and  convert to MANO format.  How can I  get parameters (such as pose，shape ，R, etc) corresponding to MANO? Thank you！ @reyuwei

**Comment by reyuwei** [comment]
Hi!
Currently, we do not have direct methods to convert NIMBLE model to MANO parameters. One way to work around it is to regress the parameters according to our MANO output using existing resources like [Minimal-IK](https://github.com/CalciferZh/Minimal-IK).

**Comment by gs-ren** [comment]
> Hi! Currently, we do not have direct methods to convert NIMBLE model to MANO parameters. One way to work around it is to regress the parameters according to our MANO output using existing resources like [Minimal-IK](https://github.com/CalciferZh/Minimal-IK).

Thank you !
